name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build, export, and upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Export
        run: yarn export
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: out
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
